### ISSUE TITLE
Extension not working on Safari for macOS Big Sur

### ISSUE THREAD

**Issue by JLDesignNetwork** [turnoffthelights/Turn-Off-the-Lights-Safari-extension#1]
As the title says, this extension for safari is not working on macOS Big Sur.  The instructions for the safari extension are also done for google chrome, so it is not clear if there are specific instructions for safari. 

Anyways, I installed the extension from the apple store and opened the app that was installed. It reports that the extension is disabled in safari. So I clicked the button to enable it, but when I open safari, the extension is not listed in the list of active extensions. There is not icon to indicate that it is enabled, and there is no way that I can find to enable it inside of the safari browser. 

Any assistance would be appreciated. Thanks.

**Comment by stefanvd** [comment]
Hi there,

That is a known issue on Apple side, that is do not index the new Safari extension on your preference page. The solution is to download and install the Safari technology preview browser. And then you should see the Turn Off the Lights Safari extension in your Safari preference -> Extensions tab.
https://developer.apple.com/safari/technology-preview/

Thanks,

**Comment by JLDesignNetwork** [comment]
Interesting. I am downloading that now to test it, but I am curious why other extensions work fine, but this one does not. I guess if the extension is not being indexed as you say, why are others indexed?

Thank you for the quick response and the info on the preview browser.

**Comment by JLDesignNetwork** [comment]
Downloaded and installed the preview browser. Interestingly enough after I installed and ran the preview browser, the TOtL extension was recognized in both the preview browser and the original safari browser. So not it works in both. But as I already noted, other extensions were recognized by the default safari browser, except this one. I would say that preview browser aided the default browser in recognition of this extension, which leads me to wonder if there is something that can be done in this extension to make it compatible with the default without having to download the preview browser.  Just a thought.

Anyways, thanks again for the response and input.

**Comment by stefanvd** [comment]
I am glad that the problem is solved. 

We have no idea here. We just click on the "archive the package" in Xcode, and then send the package to Apple Store.
Note: That other developers experience this issue too, see this official Apple developer forum:
https://developer.apple.com/forums/thread/668416

Thanks,
